### ISSUE TITLE
Not installing now

### ISSUE THREAD

**Issue by TheCoderDivine** [cybercog/laravel-clickhouse#6]
I am working on a Laravel 8 project with PHP 7.4 on my local machine, using the CyberLog Laravel ClickHouse package. However, when I tried to migrate the project to the server and perform 'composer install', I encountered an issue. It seems that the package is not supported on PHP 7.4; it requires PHP 8. How can I install this package with PHP 7.4?

**Comment by antonkomarev** [comment]
This package does not have stable version yet, and PHP 7.4 support was dropped. Now it has minimum version of PHP8 and Laravel 9. I don't really remember why I bumped requirements. Maybe I should downgrade them back.

**Comment by antonkomarev** [comment]
You can use exact hash in composer: `5020a603f88e70b97d6fea91e76a835e1c4e03e4`

**Comment by TheCoderDivine** [comment]
while executing the below command
divine@tech:  composer require cybercog/laravel-clickhouse:dev-master#5020a603f88e70b97d6fea91e76a835e1c4e03e4

./composer.json has been updated
Running composer update cybercog/laravel-clickhouse
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires cybercog/laravel-clickhouse dev-master#5020a603f88e70b97d6fea91e76a835e1c4e03e4 -> satisfiable by cybercog/laravel-clickhouse[dev-master].
    - cybercog/laravel-clickhouse dev-master requires php ^8.0 -> your php version (7.4.3) does not satisfy that requirement.

Installation failed, reverting ./composer.json to its original content.

**Comment by antonkomarev** [comment]
@TheCoderDivine try again without hash, just dev-master

**Comment by TheCoderDivine** [comment]
Thanks @antonkomarev. Now it's working. However, in the future, I will need this. Can you make it version-based?

**Comment by antonkomarev** [comment]
Sure, just need time to push it to release.
